### ISSUE TITLE
proof of font

### ISSUE THREAD

**Issue by BanjoBenjammin** [Hack-The-Tunnels-8/hack-the-tunnels-group-7-shawarma#30]
![image](https://github.com/Hack-The-Tunnels-8/hack-the-tunnels-group-7-shawarma/assets/144839119/a81fbbef-a890-4a12-b0b8-a44ab38f786a)

**Comment by BanjoBenjammin** [comment]
!review

**Comment by evanli2002** [comment]
Please don't create your own issues as the system won't process it even if we approve. Please resubmit under the correct issue
